name = "danny-tattoo-calendar-v2"
main = "src/index.js"
compatibility_date = "2026-08-31"

[assets]
directory = "./public"
binding = "ASSETS"
run_worker_first = ["/api/*"]

[vars]
CALENDAR_ID = "654fc6253ab57566dda44669f464769f87cf976b8dd6a9d47affcb4045f515a2@group.calendar.google.com"

[[services]]
binding = "BARBER"
service = "barber"
